### ISSUE TITLE
Fatal error: [localhost] /bin/sh: 1: rpm: not found

### ISSUE THREAD

**Issue by sweetfisheric** [prestodb/presto-admin#71]
Hello,

I tried to follow this page http://prestodb.github.io/presto-admin/installation/presto-server-installation.html to install Presto sever, but I got the error 'Fatal error: [localhost] /bin/sh: 1: rpm: not found.' I tried to change the permission and different Presto rpm files but haven't had good luck. I am using Ubuntu 15.04 if that matters. Thank you.

**Comment by rschlussel** [comment]
Does your os have the rpm program installed?

**Comment by brian-rickman** [comment]
Default installations of Ubuntu do not have rpm.  You should be able to get it by running "sudo apt-get install rpm"

**Comment by sweetfisheric** [comment]
Thank you. I was able to pass that after I installed Alien. I now got another error
'Deploying rpm on localhost...

Fatal error: [localhost] Needed to prompt for a connection or sudo password (host: localhost), but input would be ambiguous in parallel mode

Aborting.

My config.json file is 

{
    "username":"root",
    "coordinator":"localhost",
    "workers":[
        "localhost"
    ],
    "port":"22"
}

**Comment by brian-rickman** [comment]
This page explains how to get around that:
http://prestodb.github.io/presto-admin/ssh-configuration.html#using-presto-admin-with-ssh-passwords

Options are:
sudo ./presto-admin <command> -p <password>
or
sudo ./presto-admin <command> -I
Initial value for env.password: <type your password here>

**Comment by brian-rickman** [comment]
The primary advantage of presto-admin is that it makes it easy to operate on all the nodes of a cluster at once.

For a single node installation, I think you will be better off following the manual installation process outlined here: 
https://prestodb.io/docs/current/installation/deployment.html

**Comment by rschlussel** [comment]
presto-admin connects to the hosts through ssh (even localhost).  If you don't have passwordless ssh set up, you can run your commands with -I (that's an uppercase 'i') , and it will prompt you for a password.  Alternatively you can pass in a password using -p.
For example:
sudo ./presto-admin -I server install /path/to/presto.rpm
sudo ./presto-admin -p my-not-so-secret-password server install /path/to/presto.rpm

**Comment by mattsfuller** [comment]
@sweetfisheric did you get this figured out?

**Comment by rschlussel** [comment]
Closing, as this seems to have been resolved.

**Comment by sbmaggarwal** [comment]
@rschlussel This is still happening. When I execute the following command:
```
./presto-admin -p my-password server install ./presto-server-rpm-0.167-t.0.2.x86_64.rpm
```
I get:
```
Using rpm_specifier as a local path
Fetching local presto rpm at path: ./presto-server-rpm-0.167-t.0.2.x86_64.rpm
Found existing rpm at: ./presto-server-rpm-0.167-t.0.2.x86_64.rpm
Deploying rpm on localhost...

Fatal error: [localhost] Needed to prompt for a connection or sudo password 
    (host: localhost), but input would be ambiguous in parallel mode

Aborting.
```
I have all libraries installed like `rpm`, `python 2.7`, Java 8 and have followed all steps till [here](https://teradata.github.io/presto/docs/current/presto-admin/installation/presto-server-installation.html). My `config.json` is empty as this should make use of all default settings.

I am trying to deploy a single node Presto installation. Anything else I need to confirm?

**Comment by yuokada** [comment]
Hi, @sbmaggarwal  
Please try to use `-I` Option.
```
./presto-admin -I -p my-password server install ./presto-server-rpm-0.167-t.0.2.x86_64.rpm
```

**Comment by sbmaggarwal** [comment]
@yuokada I am not sure why this happens but when I run the above command, it deletes the `presto-server-rpm-0.167-t.0.2.x86_64.rpm` file from the directory and gives me the following error:
```
Initial value for env.password: <Here I enter my-password>
Using rpm_specifier as a local path
Fetching local presto rpm at path: ./presto-server-rpm-0.167-t.0.2.x86_64.rpm

Fatal error: [localhost] Unable to find or download presto rpm with specifier ./presto-server-rpm-0.167-t.0.2.x86_64.rpm

Aborting.
```
What can be the issue?

**Comment by mattsfuller** [comment]
What happens if you don't put the "./" on the argument? So simply enter:
./presto-admin -I -p my-password server install presto-server-rpm-0.167-t.0.2.x86_64.rpm

I'm assuming you have the rpm located in the current directory.

**Comment by yuokada** [comment]
@sbmaggarwal which version do you use?

It's not reproduce on 2.3.
